class ControllerConstants:
    BUTTON_ENGAGED_COMMAND = 0x90
    BUTTON_DISENGAGED_COMMAND = 0x80
    CONTROL_CHANGE_COMMAND = 0xB0
    BUTTON_VALUE_CHANGE_ON_COMMAND = 0x9A
    BUTTON_VALUE_CHANGE_OFF_COMMAND = 0x8A
    KNOB_VALUE_CHANGE_COMMAND = 0xBA
